### ISSUE TITLE
run issue

### ISSUE THREAD

**Issue by zzchuman** [ACabrejas/MLforFlowOptimisation#6]
Hello, ACabrejas!
  I have browsed your code，you use the vissim as the main tool to interact with DQN agent,right? Sumo is few use. If you have implemented the sumo DQN agent, could you tell me?
  Best wishes!

**Comment by zzcNEU** [comment]
I browsed your code，you use the vissim as the main tool to intereact with DQN,right? Sumo is not use.

**Comment by ACabrejas** [comment]
Hello,
Sorry I only saw this now.
The innermost component of the agent located in /Vissim/DQNAgents.py / is stripped down from the interface with VISSIM, containing only the RL necessary components.
You can use returns from SUMO's TraCI API such as `traci.lanes.getLastStepHaltingNumber()` to generate states that you can pass to the agent, integrating it in your runtime.
